version = 1

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["angular"]

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"