// <auto-generated />
using System;
using Battleship.Webapi.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Battleship.Webapi.Migrations
{
    [DbContext(typeof(PlayerDbContext))]
    [Migration("20220517053241_ModifyStats")]
    partial class ModifyStats
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Battleship.Logic.Models.Cell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("GridId")
                        .HasColumnType("int");

                    b.Property<int?>("shipId")
                        .HasColumnType("int");

                    b.Property<int>("touched")
                        .HasColumnType("int");

                    b.Property<int>("x")
                        .HasColumnType("int");

                    b.Property<int>("y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("shipId");

                    b.ToTable("Cells");
                });

            modelBuilder.Entity("Battleship.Logic.Models.Grid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Dimensions")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerOwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerOwnerId");

                    b.ToTable("Grids");
                });

            modelBuilder.Entity("Battleship.Logic.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Mail")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Battleship.Logic.Models.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsDestroyed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int?>("Orientation")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ship");
                });

            modelBuilder.Entity("Battleship.Logic.Models.Stats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Grid1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Grid2Id")
                        .HasColumnType("int");

                    b.Property<int?>("Player1Id")
                        .HasColumnType("int");

                    b.Property<int>("Player1shots")
                        .HasColumnType("int");

                    b.Property<int?>("Player2Id")
                        .HasColumnType("int");

                    b.Property<int>("Player2shots")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerTurnId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerVictoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Grid1Id");

                    b.HasIndex("Grid2Id");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.HasIndex("PlayerTurnId");

                    b.HasIndex("PlayerVictoryId");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("Battleship.Logic.Models.Cell", b =>
                {
                    b.HasOne("Battleship.Logic.Models.Ship", "ship")
                        .WithMany()
                        .HasForeignKey("shipId");

                    b.Navigation("ship");
                });

            modelBuilder.Entity("Battleship.Logic.Models.Grid", b =>
                {
                    b.HasOne("Battleship.Logic.Models.Player", "PlayerOwner")
                        .WithMany()
                        .HasForeignKey("PlayerOwnerId");

                    b.Navigation("PlayerOwner");
                });

            modelBuilder.Entity("Battleship.Logic.Models.Stats", b =>
                {
                    b.HasOne("Battleship.Logic.Models.Grid", "Grid1")
                        .WithMany()
                        .HasForeignKey("Grid1Id");

                    b.HasOne("Battleship.Logic.Models.Grid", "Grid2")
                        .WithMany()
                        .HasForeignKey("Grid2Id");

                    b.HasOne("Battleship.Logic.Models.Player", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1Id");

                    b.HasOne("Battleship.Logic.Models.Player", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2Id");

                    b.HasOne("Battleship.Logic.Models.Player", "PlayerTurn")
                        .WithMany()
                        .HasForeignKey("PlayerTurnId");

                    b.HasOne("Battleship.Logic.Models.Player", "PlayerVictory")
                        .WithMany()
                        .HasForeignKey("PlayerVictoryId");

                    b.Navigation("Grid1");

                    b.Navigation("Grid2");

                    b.Navigation("Player1");

                    b.Navigation("Player2");

                    b.Navigation("PlayerTurn");

                    b.Navigation("PlayerVictory");
                });
#pragma warning restore 612, 618
        }
    }
}
